<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Select size_gl-icon__wrapper</name>
   <tag></tag>
   <elementGuidId>b508c156-febd-4974-9ac9-aab8f1f226f7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.gl-cta.gl-cta--primary.gl-cta--full-width > span.gl-icon__wrapper</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='add-to-bag']/button/span[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>150a5b9f-b2f5-4941-9d94-81c8c18ca6c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>arrow-right-long</value>
      <webElementGuid>3a6806f1-643f-4009-b3ee-edd39c767374</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gl-icon__wrapper</value>
      <webElementGuid>5b2041fc-5f66-4e8f-acb1-2b85ca1d37eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>163e57e2-3d90-484b-8a17-3fb94e836f6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;fixed-content&quot;)/section[@class=&quot;buy-section___ZPaYL gl-vspace-bpall-medium mobile___3NCgR&quot;]/div[@id=&quot;add-to-bag&quot;]/button[@class=&quot;gl-cta gl-cta--primary gl-cta--full-width&quot;]/span[@class=&quot;gl-icon__wrapper&quot;]</value>
      <webElementGuid>224cd1fe-b129-4543-b3e7-50f2f2a5f8a1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='add-to-bag']/button/span[2]</value>
      <webElementGuid>84a415fb-f8b2-4b24-b5dc-7a7c68b6472a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select size'])[1]/following::span[1]</value>
      <webElementGuid>98a06fd2-662a-4af2-908a-5042ba98bde3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hướng dẫn chọn kích cỡ'])[1]/following::span[2]</value>
      <webElementGuid>9dfc54ab-f72b-4fd7-8d6d-885c103a92f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add to wishlist'])[1]/preceding::span[3]</value>
      <webElementGuid>e1126257-d3fc-48f6-bc58-3029844dd9b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='FREE SHIPPING FOR ADICLUB MEMBERS'])[1]/preceding::span[5]</value>
      <webElementGuid>282e1595-49cb-435a-b28a-aaf5811d803f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/button/span[2]</value>
      <webElementGuid>ca3e3ad1-d9c9-4184-a446-cfd2616540f3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
