<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Ting Vit__input_1rlri_35</name>
   <tag></tag>
   <elementGuidId>c49ccd4d-3314-4be0-80af-1292706e1fa0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input._input_1rlri_35</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div/div/div/div/div/div/div/div[3]/div/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b2a0c8b6-63d6-4c01-b2ae-54e944931f80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>tìm kiếm</value>
      <webElementGuid>702f1d78-aa7d-4b1c-b843-2395623a6e86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-auto-id</name>
      <type>Main</type>
      <value>searchinput-mobile</value>
      <webElementGuid>719e4253-7454-4aac-a81f-2f7570e2b444</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>88c21bec-0a49-48d1-84e6-89af96aca5c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocorrect</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>ad5707ae-03ae-465f-984c-36c764105891</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maximum-scale</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>e8c68491-e2f6-4037-9af5-4c682309cd2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_input_1rlri_35</value>
      <webElementGuid>92790222-c5f1-4aa4-9f5b-d7f9010265dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;gl-app&quot;]/div[1]/div[@class=&quot;content-wrapper___1xMQS content-visibility-enabled___2aojn&quot;]/div[@class=&quot;sheet___2Zvfp page-content___2Bh3s&quot;]/div[1]/div[@class=&quot;_wrapper_1spbu_7 _sticky_1spbu_13&quot;]/div[@class=&quot;gl-app&quot;]/div[@class=&quot;_search-panel_1rlri_1 _is-open_1rlri_22&quot;]/div[@class=&quot;_search-box_1rlri_27&quot;]/input[@class=&quot;_input_1rlri_35&quot;]</value>
      <webElementGuid>753f7ca9-2ae2-4998-9bc7-eaf8f43a7ee9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div/div/div/div/div/div/div[3]/div/input</value>
      <webElementGuid>21a1ded7-493b-425c-a839-b4cddb652450</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/input</value>
      <webElementGuid>183466f6-fef5-46c7-88a5-314c60a0b697</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'tìm kiếm']</value>
      <webElementGuid>6ab2e443-250f-49c3-a068-62f6990c5e10</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
