<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_TIP TC_account-portal-close</name>
   <tag></tag>
   <elementGuidId>f656eb05-91e1-463c-b83f-da74da0412c9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button[name=&quot;account-portal-close&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@name='account-portal-close']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>e59aac9c-a60f-49f5-9219-4906c1c49673</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>account-portal-close</value>
      <webElementGuid>4b07e9ee-a692-4640-8c10-a1794d87d64a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>d743fe76-1fc7-47e4-a036-088471784024</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gl-modal__close</value>
      <webElementGuid>3885dfdb-f7a5-4f2c-884f-bb8fd918b820</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;account-portal-modal&quot;)/div[@class=&quot;gl-modal gl-modal--mobile-full gl-modal--active gl-modal--full-mobile gl-modal--no-animation _account-portal-modal_1auzo_1 modal-position___NzK_w&quot;]/div[@class=&quot;gl-modal__dialog gl-modal__dialog--full-mobile&quot;]/button[@class=&quot;gl-modal__close&quot;]</value>
      <webElementGuid>2412e89e-76da-4a4e-8402-fe7aeb435737</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@name='account-portal-close']</value>
      <webElementGuid>cbce3cf9-6e8c-49d8-ba61-55097779e2c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='account-portal-modal']/div/div/button</value>
      <webElementGuid>d5c4f717-828d-4242-ad17-bba05611ce57</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TIẾP TỤC'])[1]/following::button[1]</value>
      <webElementGuid>f0c126a0-2ac5-484f-9546-61cea7d0301b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Thêm thông tin'])[1]/following::button[2]</value>
      <webElementGuid>8854c85f-77ff-493b-97b8-2b1bb7027ac6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Join adiclub. GET INSTANT REWARDS.'])[1]/preceding::button[1]</value>
      <webElementGuid>5873d3ee-1173-4e56-9e13-f2c2d78ac9b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Not a member? Join adiClub for free and unlock these benefits immediately:'])[1]/preceding::button[1]</value>
      <webElementGuid>7bccc0e4-446b-44cc-9649-6867f45bc291</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/button</value>
      <webElementGuid>10b39a18-0591-4207-8492-47f459974894</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@name = 'account-portal-close' and @type = 'button']</value>
      <webElementGuid>ecda8bec-2789-4f42-9ca6-b7b99ee75a60</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
