<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Ting Vit__input_1rlri_35</name>
   <tag></tag>
   <elementGuidId>4860b8fb-ac1a-4120-8cf6-70d0c8635f72</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input._input_1rlri_35</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div/div/div/div/div/div/div/div[3]/div/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f95491f9-cda4-43b3-b517-be3d870de98c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>tìm kiếm</value>
      <webElementGuid>3bd7d4b6-2cf2-4ec5-9677-255d0d08b8bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-auto-id</name>
      <type>Main</type>
      <value>searchinput-mobile</value>
      <webElementGuid>a0339dcd-8da6-4e91-ba9e-85db5ef33273</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>62120b27-95c6-43f3-8498-90262542e2c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocorrect</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>54d3411e-c886-41dd-bce3-61cb8d004353</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maximum-scale</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>b7121e1d-d29e-4e61-a7fd-fe9346093367</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_input_1rlri_35</value>
      <webElementGuid>4091eb3b-b80b-4301-b14c-3b14183119f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;gl-app&quot;]/div[1]/div[@class=&quot;content-wrapper___1xMQS content-visibility-enabled___2aojn&quot;]/div[@class=&quot;sheet___2Zvfp page-content___2Bh3s&quot;]/div[1]/div[@class=&quot;_wrapper_1spbu_7 _sticky_1spbu_13&quot;]/div[@class=&quot;gl-app&quot;]/div[@class=&quot;_search-panel_1rlri_1 _is-open_1rlri_22&quot;]/div[@class=&quot;_search-box_1rlri_27&quot;]/input[@class=&quot;_input_1rlri_35&quot;]</value>
      <webElementGuid>65981d65-060f-4af8-9a93-e4f29d6d070b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div/div/div/div/div/div/div[3]/div/input</value>
      <webElementGuid>6351f1ed-aa35-44b6-9ac7-7501a287b13d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/input</value>
      <webElementGuid>47a6e561-41c7-4955-be36-710f041ccca6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'tìm kiếm']</value>
      <webElementGuid>f34f0592-be82-4a16-bf94-38a1fc7f4502</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
