<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Thanh thiu nin (8-16)_gl-icon__wrapper</name>
   <tag></tag>
   <elementGuidId>ce359649-2db2-4d1a-b6eb-6dae849a9968</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button._mobile_search_toggle_4re0c_1 > span.gl-icon__wrapper</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div/div/div/div/div/div/div/header/div[2]/div/div[2]/button/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>ecb5b087-42e8-423e-9ab2-46350288fd47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gl-icon__wrapper</value>
      <webElementGuid>af830ed8-323f-4425-9b90-172a6f94e541</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>3fca3430-6fd3-4bb6-b99c-fdcebc5bafbe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;gl-app&quot;]/div[1]/div[@class=&quot;content-wrapper___1xMQS content-visibility-enabled___2aojn&quot;]/div[@class=&quot;sheet___2Zvfp page-content___2Bh3s&quot;]/div[1]/div[@class=&quot;_wrapper_1spbu_7 _sticky_1spbu_13&quot;]/div[@class=&quot;gl-app&quot;]/header[@class=&quot;_header_1spbu_25 _scroll_effect_74if6_1&quot;]/div[@class=&quot;_header_container_1spbu_30&quot;]/div[@class=&quot;_header_bottom_558sn_1&quot;]/div[@class=&quot;_auxiliary_menu_558sn_31&quot;]/button[@class=&quot;_mobile_search_toggle_4re0c_1&quot;]/span[@class=&quot;gl-icon__wrapper&quot;]</value>
      <webElementGuid>c57dbaba-2a2b-4ec9-93f9-22ab9e8edee9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div/div/div/div/div/div/header/div[2]/div/div[2]/button/span</value>
      <webElementGuid>05691cb9-f782-42cf-9532-a61b82144fdf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Thanh thiếu niên (8-16)'])[1]/following::span[4]</value>
      <webElementGuid>c3567a60-8c8f-4d8b-ad4c-cebcb270f044</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Trẻ em (4-8)'])[1]/following::span[4]</value>
      <webElementGuid>0696e1ba-bbda-4355-aa4f-88a533037b61</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Túi của bạn trống'])[1]/preceding::span[2]</value>
      <webElementGuid>62eba311-f5ab-4e64-bd40-a5c45088b750</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='NAM'])[2]/preceding::span[4]</value>
      <webElementGuid>bbd4d02a-831c-44b3-b98e-0060152d4d9f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/button/span</value>
      <webElementGuid>d8b52975-974a-4f73-83bc-41217efc5d29</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
